import { Sidebar } from '@/components/Sidebar/Sidebar';
import './app.css';
import { Noto_Sans_KR } from 'next/font/google';
import { Header } from '@/components/Header/Header';
import { Footer } from '@/components/Footer/Footer';
import classNames from 'classnames';
import styles from './layout.module.css';

// const inter = Noto_Sans_KR({ subsets: ['latin'] })
const inter = Noto_Sans_KR({
  weight: ['300', '400', '700', '900'],
  subsets: ['latin'],
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={classNames([inter.className, styles.wrapper])}>
        <Header className={styles.header} />
        <Sidebar className={styles.sidebar} />
        <div className={styles.body}>{children}</div>
        <Footer className={styles.footer} />
      </body>
    </html>
  );
}
